import {
  AspectRatio,
  CameraHeight,
  CameraMovement,
  CameraRigType,
  LightFixtureType,
  PropType,
  SceneSetup,
  SensorFormat,
  ShotSize,
} from '../types';
import { calculateFovAngle } from '../utils/geometry';

export const FOCAL_LENGTH_PRESETS = [14, 18, 24, 28, 35, 50, 75, 85, 105, 135, 200];

export const ASPECT_RATIOS: { value: AspectRatio; label: string; ratio: number }[] = [
  { value: '16:9', label: '16:9 (1.78:1 HD/UHD)', ratio: 16 / 9 },
  { value: '2.39:1', label: '2.39:1 (Anamorphic Scope)', ratio: 2.39 },
  { value: '1.85:1', label: '1.85:1 (Theatrical Flat)', ratio: 1.85 },
  { value: '4:3', label: '4:3 (Classic Academy 1.33:1)', ratio: 4 / 3 },
  { value: '9:16', label: '9:16 (Vertical Video)', ratio: 9 / 16 },
];

export const SENSOR_FORMATS: { value: SensorFormat; label: string }[] = [
  { value: 'Super35', label: 'Super 35 (Standard Cinema)' },
  { value: 'FullFrame', label: 'Full Frame / 35mm VistaVision' },
  { value: 'LargeFormat', label: 'Large Format (ARRI LF / Alexa 65)' },
  { value: 'MFT', label: 'Micro 4/3 (Pocket Cinema)' },
];

export const CAMERA_HEIGHTS: { value: CameraHeight; label: string }[] = [
  { value: 'Ground', label: 'Ground Level (0-1 ft)' },
  { value: 'Knee', label: 'Knee Level (2 ft)' },
  { value: 'Waist', label: 'Waist / Hip Level (3-4 ft)' },
  { value: 'Eye Level', label: 'Eye Level (5-6 ft)' },
  { value: 'High', label: 'High Angle (7-9 ft)' },
  { value: 'Overhead / Bird\'s Eye', label: 'Overhead / Bird\'s Eye' },
];

export const CAMERA_RIGS: { value: CameraRigType; label: string; icon: string }[] = [
  { value: 'Tripod', label: 'Tripod (Locked off)', icon: 'camera' },
  { value: 'Dana Dolly', label: 'Dana Dolly / Rail Track', icon: 'rail-symbol' },
  { value: 'Slider', label: 'Camera Slider Track', icon: 'move-horizontal' },
  { value: 'Steadicam', label: 'Steadicam / Snorricam Vest', icon: 'navigation' },
  { value: 'Handheld', label: 'Handheld / Shoulder Rig', icon: 'hand' },
  { value: 'Gimbal', label: 'Motorized 3-Axis Gimbal (Ronin)', icon: 'compass' },
  { value: 'Jib / Crane', label: 'Jib Arm / Crane Boom', icon: 'maximize-2' },
  { value: 'TechnoCrane', label: 'TechnoCrane (Telescopic)', icon: 'sliders' },
  { value: 'Car Mount', label: 'Car Mount / Hostess Tray', icon: 'truck' },
  { value: 'Drone', label: 'Aerial Drone Quadcopter', icon: 'wind' },
  { value: 'Cable Cam', label: 'Cable Cam Aerial Rig', icon: 'anchor' },
];

export const SHOT_SIZES: {
  value: ShotSize;
  code: string;
  name: string;
  description: string;
  badgeBg: string;
}[] = [
  {
    value: 'ELS',
    code: 'ELS',
    name: 'Extreme Long Shot',
    description: 'Vast environment where subject is tiny; establishes geography and scale.',
    badgeBg: 'bg-indigo-900/60 text-indigo-300 border-indigo-700/50',
  },
  {
    value: 'WS',
    code: 'WS',
    name: 'Wide Shot / Master',
    description: 'Subject fits head to toe with surrounding environment clearly visible.',
    badgeBg: 'bg-blue-900/60 text-blue-300 border-blue-700/50',
  },
  {
    value: 'FS',
    code: 'FS',
    name: 'Full Shot',
    description: 'Frames entire character from head to feet, emphasizing posture and action.',
    badgeBg: 'bg-sky-900/60 text-sky-300 border-sky-700/50',
  },
  {
    value: 'MWS',
    code: 'MWS',
    name: 'Medium Wide (Cowboy)',
    description: 'Framed from mid-thigh up; traditional western framing.',
    badgeBg: 'bg-emerald-900/60 text-emerald-300 border-emerald-700/50',
  },
  {
    value: 'MS',
    code: 'MS',
    name: 'Medium Shot',
    description: 'Framed from waist up; standard conversation framing for physical gesture.',
    badgeBg: 'bg-amber-900/60 text-amber-300 border-amber-700/50',
  },
  {
    value: 'MCU',
    code: 'MCU',
    name: 'Medium Close-Up',
    description: 'Framed from chest/bust up; focuses on facial emotion while keeping context.',
    badgeBg: 'bg-orange-900/60 text-orange-300 border-orange-700/50',
  },
  {
    value: 'CU',
    code: 'CU',
    name: 'Close-Up',
    description: 'Frames face from neck up; intense emotional resonance.',
    badgeBg: 'bg-rose-900/60 text-rose-300 border-rose-700/50',
  },
  {
    value: 'ECU',
    code: 'ECU',
    name: 'Extreme Close-Up',
    description: 'Tight focus on eyes, lips, or single critical physical detail.',
    badgeBg: 'bg-pink-900/60 text-pink-300 border-pink-700/50',
  },
  {
    value: 'OTS',
    code: 'OTS',
    name: 'Over the Shoulder',
    description: 'Shot from behind one subject looking at another; establishes 3D conversation space.',
    badgeBg: 'bg-purple-900/60 text-purple-300 border-purple-700/50',
  },
  {
    value: 'POV',
    code: 'POV',
    name: 'Point of View',
    description: 'Directly replicates what a character sees through their eyes.',
    badgeBg: 'bg-violet-900/60 text-violet-300 border-violet-700/50',
  },
  {
    value: 'Insert',
    code: 'INS',
    name: 'Insert / Cutaway',
    description: 'Close shot of an object, letter, phone screen, clock, or weapon.',
    badgeBg: 'bg-teal-900/60 text-teal-300 border-teal-700/50',
  },
  {
    value: 'Dutch',
    code: 'DUT',
    name: 'Dutch Angle',
    description: 'Tilted horizon creating psychological unease or dynamic tension.',
    badgeBg: 'bg-red-900/60 text-red-300 border-red-700/50',
  },
];

export const CAMERA_MOVEMENTS: { value: CameraMovement; label: string }[] = [
  { value: 'Static', label: 'Static (Locked Off)' },
  { value: 'Pan', label: 'Pan (Horizontal rotation)' },
  { value: 'Tilt', label: 'Tilt (Vertical rotation)' },
  { value: 'Dolly In', label: 'Dolly In (Push In)' },
  { value: 'Dolly Out', label: 'Dolly Out (Pull Out)' },
  { value: 'Tracking', label: 'Tracking / Lateral Dolly' },
  { value: 'Pedestal', label: 'Pedestal (Move straight up/down)' },
  { value: 'Boom / Crane', label: 'Boom / Crane Sweep' },
  { value: 'Handheld', label: 'Handheld Kinetic' },
  { value: 'Steadicam', label: 'Steadicam Dynamic Walk' },
  { value: 'Whip Pan', label: 'Whip Pan / Swish' },
  { value: 'Zoom', label: 'Optical / Crash Zoom' },
];

export const LIGHT_FIXTURES: {
  type: LightFixtureType;
  name: string;
  defaultBeam: number;
  defaultTemp: number;
  defaultModel: string;
}[] = [
  {
    type: 'fresnel',
    name: 'Fresnel Spotlight',
    defaultBeam: 35,
    defaultTemp: 3200,
    defaultModel: 'ARRI 1K Tungsten Fresnel',
  },
  {
    type: 'led_panel',
    name: 'Soft LED Panel',
    defaultBeam: 110,
    defaultTemp: 5600,
    defaultModel: 'ARRI SkyPanel S60-C',
  },
  {
    type: 'softbox',
    name: 'Bowens Softbox Dome',
    defaultBeam: 90,
    defaultTemp: 5600,
    defaultModel: 'Aputure Light Storm 600d + Light Dome',
  },
  {
    type: 'spotlight',
    name: 'Hard Leko / Ellipsoidal',
    defaultBeam: 19,
    defaultTemp: 5600,
    defaultModel: 'ETC Source Four / Aputure Spotlight Mount',
  },
  {
    type: 'tube_light',
    name: 'Pixel LED Tube',
    defaultBeam: 160,
    defaultTemp: 5600,
    defaultModel: 'Astera Titan Tube FP1',
  },
  {
    type: 'china_ball',
    name: 'China Ball / Lantern Diffuser',
    defaultBeam: 360,
    defaultTemp: 3200,
    defaultModel: 'Chimera 30" China Ball Lantern',
  },
  {
    type: 'practical',
    name: 'Practical Lamp / Bulb',
    defaultBeam: 360,
    defaultTemp: 2700,
    defaultModel: 'Tungsten Table Lamp / Aputure B7c',
  },
  {
    type: 'reflector',
    name: 'Reflector Bounce Board',
    defaultBeam: 75,
    defaultTemp: 5600,
    defaultModel: '4x4 Foamcore / Beadboard Bounce',
  },
  {
    type: 'c_stand_flag',
    name: 'C-Stand Solid Flag (Negative Fill)',
    defaultBeam: 0,
    defaultTemp: 0,
    defaultModel: 'Matthews 24x36 Solid Flag',
  },
  {
    type: 'overhead_diffusion',
    name: 'Overhead 8x8 Diffusion Frame',
    defaultBeam: 120,
    defaultTemp: 5600,
    defaultModel: '8x8 Silent Frost Silk Frame',
  },
];

export const PROP_CATALOG: {
  type: PropType;
  name: string;
  category: 'Living' | 'Dining & Office' | 'Bedroom' | 'Studio & Stage' | 'Vehicles' | 'Architecture' | 'Generic';
  defaultWidth: number;
  defaultHeight: number;
  defaultColor: string;
}[] = [
  // Living
  { type: 'sofa', name: 'Couch / 3-Seat Sofa', category: 'Living', defaultWidth: 160, defaultHeight: 70, defaultColor: '#475569' },
  { type: 'sofa_sectional', name: 'L-Sectional Couch', category: 'Living', defaultWidth: 200, defaultHeight: 180, defaultColor: '#334155' },
  { type: 'armchair', name: 'Armchair / Recliner', category: 'Living', defaultWidth: 75, defaultHeight: 75, defaultColor: '#64748b' },
  { type: 'table_coffee', name: 'Coffee Table', category: 'Living', defaultWidth: 100, defaultHeight: 50, defaultColor: '#92400e' },
  { type: 'tv', name: 'Television & Media Stand', category: 'Living', defaultWidth: 120, defaultHeight: 30, defaultColor: '#1e293b' },
  { type: 'bookshelf', name: 'Bookshelf / Storage', category: 'Living', defaultWidth: 120, defaultHeight: 35, defaultColor: '#78350f' },
  { type: 'plant', name: 'Potted Plant / Tree', category: 'Living', defaultWidth: 45, defaultHeight: 45, defaultColor: '#15803d' },

  // Dining & Office
  { type: 'dining_set', name: 'Dining Table + 4 Chairs', category: 'Dining & Office', defaultWidth: 160, defaultHeight: 120, defaultColor: '#7c2d12' },
  { type: 'table_rect', name: 'Rectangular Table', category: 'Dining & Office', defaultWidth: 140, defaultHeight: 70, defaultColor: '#854d0e' },
  { type: 'table_round', name: 'Round Dining Table', category: 'Dining & Office', defaultWidth: 90, defaultHeight: 90, defaultColor: '#854d0e' },
  { type: 'chair', name: 'Dining Chair', category: 'Dining & Office', defaultWidth: 40, defaultHeight: 40, defaultColor: '#a16207' },
  { type: 'desk', name: 'Executive Office Desk', category: 'Dining & Office', defaultWidth: 140, defaultHeight: 70, defaultColor: '#334155' },
  { type: 'bar_counter', name: 'Bar Counter', category: 'Dining & Office', defaultWidth: 180, defaultHeight: 50, defaultColor: '#713f12' },
  { type: 'bar_stool', name: 'Bar Stool', category: 'Dining & Office', defaultWidth: 35, defaultHeight: 35, defaultColor: '#ca8a04' },

  // Bedroom
  { type: 'bed_king', name: 'King Size Bed', category: 'Bedroom', defaultWidth: 180, defaultHeight: 200, defaultColor: '#475569' },
  { type: 'bed', name: 'Double / Queen Bed', category: 'Bedroom', defaultWidth: 150, defaultHeight: 180, defaultColor: '#64748b' },
  { type: 'nightstand', name: 'Nightstand', category: 'Bedroom', defaultWidth: 45, defaultHeight: 45, defaultColor: '#78350f' },
  { type: 'wardrobe', name: 'Wardrobe / Closet', category: 'Bedroom', defaultWidth: 140, defaultHeight: 60, defaultColor: '#52525b' },

  // Studio & Stage Equipment
  { type: 'c_stand', name: 'C-Stand + Arm Grip', category: 'Studio & Stage', defaultWidth: 40, defaultHeight: 40, defaultColor: '#64748b' },
  { type: 'sound_boom', name: 'Sound Boom Operator', category: 'Studio & Stage', defaultWidth: 50, defaultHeight: 50, defaultColor: '#d97706' },
  { type: 'director_chair', name: "Director's Folding Chair", category: 'Studio & Stage', defaultWidth: 45, defaultHeight: 45, defaultColor: '#1e293b' },
  { type: 'apple_box', name: 'Apple Box (Full/Half)', category: 'Studio & Stage', defaultWidth: 40, defaultHeight: 30, defaultColor: '#b45309' },
  { type: 'camera_cart', name: 'Camera Magliner Cart', category: 'Studio & Stage', defaultWidth: 110, defaultHeight: 55, defaultColor: '#475569' },
  { type: 'green_screen', name: 'Chroma Green / Seamless Backdrop', category: 'Studio & Stage', defaultWidth: 240, defaultHeight: 20, defaultColor: '#16a34a' },

  // Vehicles
  { type: 'car', name: 'Sedan Passenger Car', category: 'Vehicles', defaultWidth: 180, defaultHeight: 360, defaultColor: '#2563eb' },
  { type: 'vehicle_suv', name: 'SUV / 4x4 Vehicle', category: 'Vehicles', defaultWidth: 200, defaultHeight: 400, defaultColor: '#475569' },
  { type: 'vehicle_truck', name: 'Production Grip Truck', category: 'Vehicles', defaultWidth: 220, defaultHeight: 520, defaultColor: '#334155' },
  { type: 'vehicle_police', name: 'Police Cruiser', category: 'Vehicles', defaultWidth: 190, defaultHeight: 380, defaultColor: '#0284c7' },

  // Architecture & Generic
  { type: 'stairs', name: 'Staircase Flight', category: 'Architecture', defaultWidth: 100, defaultHeight: 180, defaultColor: '#475569' },
  { type: 'box', name: 'Generic Box / Block', category: 'Generic', defaultWidth: 60, defaultHeight: 60, defaultColor: '#64748b' },
  { type: 'circle', name: 'Generic Pillar / Circle', category: 'Generic', defaultWidth: 50, defaultHeight: 50, defaultColor: '#64748b' },
];

export const ACTOR_COLOR_PALETTE = [
  '#3b82f6', // Blue
  '#ef4444', // Red
  '#10b981', // Emerald
  '#f59e0b', // Amber
  '#8b5cf6', // Purple
  '#ec4899', // Pink
  '#06b6d4', // Cyan
  '#f97316', // Orange
];

export const CAMERA_COLOR_PALETTE = [
  '#0284c7', // Sky Blue (Cam A)
  '#dc2626', // Crimson (Cam B)
  '#16a34a', // Green (Cam C)
  '#9333ea', // Purple (Cam D)
  '#ea580c', // Orange (Cam E)
];

// Sample Scenes for Film Students & Directors
export const SAMPLE_SCENES: SceneSetup[] = [
  {
    id: 'setup-dialogue-classic',
    name: 'Classic Dialogue (Shot-Reverse-Shot + Master)',
    sceneNumber: '1',
    scriptPage: 'p. 1-3',
    location: 'INT. LIVING ROOM - NIGHT',
    timeOfDay: 'Night INT',
    currentBeat: 1,
    totalBeats: 3,
    canvasScale: 1,
    canvasOffset: { x: 50, y: 50 },
    gridSettings: {
      size: 30,
      snap: true,
      showGrid: true,
      unit: 'm',
      pixelsPerUnit: 30,
    },
    elements: [
      // Walls for a living room
      {
        id: 'wall-1',
        type: 'wall',
        name: 'North Wall',
        x: 100,
        y: 100,
        x2: 700,
        y2: 100,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'wall-2',
        type: 'wall',
        name: 'West Wall',
        x: 100,
        y: 100,
        x2: 100,
        y2: 550,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'wall-3',
        type: 'wall',
        name: 'South Wall',
        x: 100,
        y: 550,
        x2: 700,
        y2: 550,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'wall-4',
        type: 'wall',
        name: 'East Wall',
        x: 700,
        y: 100,
        x2: 700,
        y2: 550,
        thickness: 12,
        rotation: 0,
      },
      // Door & Window
      {
        id: 'door-1',
        type: 'door',
        name: 'Entry Door',
        x: 700,
        y: 350,
        rotation: 90,
        width: 60,
        swingAngle: 90,
        swingDirection: 'left',
      },
      {
        id: 'window-1',
        type: 'window',
        name: 'Large Bay Window',
        x: 400,
        y: 100,
        rotation: 0,
        width: 140,
        depth: 15,
      },
      // Table & Chairs
      {
        id: 'prop-table',
        type: 'prop',
        propType: 'table_rect',
        name: 'Coffee Table',
        x: 400,
        y: 320,
        rotation: 0,
        width: 120,
        height: 60,
        color: '#78350f',
      },
      {
        id: 'prop-sofa',
        type: 'prop',
        propType: 'sofa',
        name: 'Main Sofa',
        x: 400,
        y: 220,
        rotation: 0,
        width: 160,
        height: 55,
        color: '#334155',
      },
      {
        id: 'prop-chair',
        type: 'prop',
        propType: 'chair',
        name: 'Armchair',
        x: 400,
        y: 420,
        rotation: 180,
        width: 50,
        height: 50,
        color: '#475569',
      },
      // Actor 1 (Alex - Sitting on Sofa)
      {
        id: 'actor-alex',
        type: 'actor',
        name: 'ALEX',
        characterLetter: 'A',
        color: '#3b82f6',
        x: 400,
        y: 240,
        rotation: 90, // facing South towards Sarah
        isStanding: false,
        actionNotes: 'Confronts Sarah about the missing ledger, remains seated.',
        path: [
          { id: 'wp-a1', x: 400, y: 240, rotation: 90, beat: 1 },
          { id: 'wp-a2', x: 400, y: 240, rotation: 90, beat: 2 },
          { id: 'wp-a3', x: 400, y: 220, rotation: 90, beat: 3 },
        ],
      },
      // Actor 2 (Sarah - Seated in Armchair, then walks to door)
      {
        id: 'actor-sarah',
        type: 'actor',
        name: 'SARAH',
        characterLetter: 'S',
        color: '#ef4444',
        x: 400,
        y: 400,
        rotation: 270, // facing North towards Alex
        isStanding: false,
        actionNotes: 'Defensive, stands up on Beat 2 and walks toward door.',
        path: [
          { id: 'wp-s1', x: 400, y: 400, rotation: 270, beat: 1 },
          { id: 'wp-s2', x: 480, y: 380, rotation: 320, beat: 2 },
          { id: 'wp-s3', x: 620, y: 350, rotation: 0, beat: 3 },
        ],
      },
      // Lighting setup (Three-point lighting + practical)
      {
        id: 'light-key',
        type: 'light',
        name: 'Key Light (SkyPanel S60)',
        fixtureType: 'softbox',
        x: 240,
        y: 260,
        rotation: 35,
        colorTemp: 4500,
        intensity: 85,
        beamAngle: 75,
        throwDistance: 240,
        fixtureModel: 'Aputure 600d + Light Dome II',
      },
      {
        id: 'light-fill',
        type: 'light',
        name: 'Fill Light (Foamcore Bounce)',
        fixtureType: 'reflector',
        x: 550,
        y: 260,
        rotation: 145,
        colorTemp: 4500,
        intensity: 40,
        beamAngle: 90,
        throwDistance: 180,
        fixtureModel: '4x4 White Beadboard Bounce',
      },
      {
        id: 'light-back',
        type: 'light',
        name: 'Hair / Rim Light (Titan Tube)',
        fixtureType: 'tube_light',
        x: 400,
        y: 130,
        rotation: 90,
        colorTemp: 5600,
        intensity: 60,
        beamAngle: 120,
        throwDistance: 150,
        fixtureModel: 'Astera Titan Tube',
      },
      // Camera A: Master Wide Shot (establishing the room and both subjects)
      {
        id: 'cam-a',
        type: 'camera',
        name: 'Cam A',
        cameraLabel: 'A',
        color: '#0284c7',
        x: 180,
        y: 320,
        rotation: 0, // facing East
        focalLength: 24,
        sensorFormat: 'Super35',
        fovAngle: calculateFovAngle(24, 'Super35'),
        aspectRatio: '2.39:1',
        cameraHeight: 'Eye Level',
        rigType: 'Tripod',
        throwDistance: 320,
        associatedShotId: 'shot-1a',
        cameraModel: 'ARRI Alexa Mini LF',
        path: [],
      },
      // Camera B: Over-the-Shoulder on Sarah (favoring Alex CU)
      {
        id: 'cam-b',
        type: 'camera',
        name: 'Cam B',
        cameraLabel: 'B',
        color: '#dc2626',
        x: 480,
        y: 450,
        rotation: 295,
        focalLength: 50,
        sensorFormat: 'Super35',
        fovAngle: calculateFovAngle(50, 'Super35'),
        aspectRatio: '2.39:1',
        cameraHeight: 'Eye Level',
        rigType: 'Dana Dolly',
        throwDistance: 280,
        associatedShotId: 'shot-1b',
        cameraModel: 'ARRI Alexa Mini LF',
        path: [],
      },
      // Camera C: Over-the-Shoulder on Alex (favoring Sarah CU & Dolly push)
      {
        id: 'cam-c',
        type: 'camera',
        name: 'Cam C',
        cameraLabel: 'C',
        color: '#16a34a',
        x: 480,
        y: 190,
        rotation: 65,
        focalLength: 85,
        sensorFormat: 'Super35',
        fovAngle: calculateFovAngle(85, 'Super35'),
        aspectRatio: '2.39:1',
        cameraHeight: 'Eye Level',
        rigType: 'Dana Dolly',
        throwDistance: 300,
        associatedShotId: 'shot-1c',
        cameraModel: 'ARRI Alexa Mini LF',
        path: [
          { id: 'wp-c1', x: 480, y: 190, rotation: 65, beat: 1 },
          { id: 'wp-c2', x: 530, y: 220, rotation: 80, beat: 2 },
          { id: 'wp-c3', x: 580, y: 260, rotation: 95, beat: 3 },
        ],
      },
    ],
    shots: [
      {
        id: 'shot-1a',
        sceneNumber: '1',
        shotNumber: '1/1',
        name: 'Master Wide - Living Room Confrontation',
        cameraId: 'cam-a',
        cameraLabel: 'A',
        shotSize: 'WS',
        lensMm: 24,
        cameraAngle: 'Eye Level',
        movement: 'Static',
        aspectRatio: '2.39:1',
        frameRate: 24,
        subjectActorIds: ['actor-alex', 'actor-sarah'],
        equipmentNotes: 'ARRI Alexa Mini + Zeiss Supreme 24mm on Sachtler 18 Tripod',
        framingDescription: 'Deep profile wide showing Alex on sofa (left-center) and Sarah in armchair (right-center), doorway in deep background.',
        actionScriptNotes: 'Holds through entire dialogue exchange; establishes room geography and tension.',
        status: 'ready',
        takesCount: 3,
        estDurationSeconds: 45,
        order: 1,
      },
      {
        id: 'shot-1b',
        sceneNumber: '1',
        shotNumber: '1/2',
        name: 'Alex OTS / Medium Close-Up',
        cameraId: 'cam-b',
        cameraLabel: 'A',
        shotSize: 'MCU',
        lensMm: 50,
        cameraAngle: 'Eye Level',
        movement: 'Static',
        aspectRatio: '2.39:1',
        frameRate: 24,
        subjectActorIds: ['actor-alex'],
        equipmentNotes: 'Cooke S4/i 50mm Prime, T2.0 for shallow depth of field isolating Alex.',
        framingDescription: 'Sarah dirty shoulder in soft foreground right, Alex framed in sharp focus on the left third.',
        actionScriptNotes: 'Delivers line: "Where did you put it, Sarah?" Captures micro-expressions of guilt.',
        status: 'planned',
        takesCount: 0,
        estDurationSeconds: 25,
        order: 2,
      },
      {
        id: 'shot-1c',
        sceneNumber: '1',
        shotNumber: '1/3',
        name: 'Sarah OTS / Push-In Close-Up & Stand',
        cameraId: 'cam-c',
        cameraLabel: 'A',
        shotSize: 'CU',
        lensMm: 85,
        cameraAngle: 'Eye Level',
        movement: 'Dolly In',
        aspectRatio: '2.39:1',
        frameRate: 24,
        subjectActorIds: ['actor-sarah'],
        equipmentNotes: 'Dana Dolly on 6ft speed rail with 85mm Prime, fluid pan follow.',
        framingDescription: 'Tight close up on Sarah. Dolly slowly pushes in as she denies the theft, panning with her as she stands.',
        actionScriptNotes: 'Sarah: "I don\'t know what you are talking about." Stands on Beat 2 and exits.',
        status: 'planned',
        takesCount: 0,
        estDurationSeconds: 30,
        order: 3,
      },
    ],
  },
  {
    id: 'setup-noir-interrogation',
    name: 'Noir Interrogation (Dramatic Key & Window Shadow)',
    sceneNumber: '2',
    scriptPage: 'p. 8-10',
    location: 'INT. POLICE INTERROGATION ROOM - NIGHT',
    timeOfDay: 'Night INT',
    currentBeat: 1,
    totalBeats: 2,
    canvasScale: 1,
    canvasOffset: { x: 50, y: 50 },
    gridSettings: {
      size: 30,
      snap: true,
      showGrid: true,
      unit: 'ft',
      pixelsPerUnit: 25,
    },
    elements: [
      {
        id: 'noir-wall-n',
        type: 'wall',
        name: 'North Wall',
        x: 150,
        y: 120,
        x2: 650,
        y2: 120,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'noir-wall-w',
        type: 'wall',
        name: 'West Wall (Two-way mirror)',
        x: 150,
        y: 120,
        x2: 150,
        y2: 500,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'noir-wall-s',
        type: 'wall',
        name: 'South Wall',
        x: 150,
        y: 500,
        x2: 650,
        y2: 500,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'noir-wall-e',
        type: 'wall',
        name: 'East Wall',
        x: 650,
        y: 120,
        x2: 650,
        y2: 500,
        thickness: 12,
        rotation: 0,
      },
      {
        id: 'noir-door',
        type: 'door',
        name: 'Heavy Steel Door',
        x: 650,
        y: 200,
        rotation: 90,
        width: 60,
        swingAngle: 90,
        swingDirection: 'left',
      },
      // Table & 2 Chairs
      {
        id: 'noir-table',
        type: 'prop',
        propType: 'desk',
        name: 'Metal Interrogation Table',
        x: 400,
        y: 310,
        rotation: 0,
        width: 140,
        height: 70,
        color: '#334155',
      },
      {
        id: 'noir-chair-suspect',
        type: 'prop',
        propType: 'chair',
        name: 'Suspect Chair (Bolted)',
        x: 330,
        y: 310,
        rotation: 90,
        width: 40,
        height: 40,
        color: '#475569',
      },
      {
        id: 'noir-chair-detective',
        type: 'prop',
        propType: 'chair',
        name: 'Detective Chair',
        x: 470,
        y: 310,
        rotation: 270,
        width: 40,
        height: 40,
        color: '#475569',
      },
      // Suspect
      {
        id: 'actor-suspect',
        type: 'actor',
        name: 'SUSPECT (MARCUS)',
        characterLetter: 'M',
        color: '#ef4444',
        x: 330,
        y: 310,
        rotation: 0, // facing East at Detective
        isStanding: false,
        actionNotes: 'Handcuffed to the table, looking defiant and sweaty.',
        path: [],
      },
      // Detective
      {
        id: 'actor-detective',
        type: 'actor',
        name: 'DET. MILLER',
        characterLetter: 'D',
        color: '#3b82f6',
        x: 470,
        y: 310,
        rotation: 180, // facing West at Suspect
        isStanding: false,
        actionNotes: 'Paces around Marcus on Beat 2.',
        path: [
          { id: 'wp-d1', x: 470, y: 310, rotation: 180, beat: 1 },
          { id: 'wp-d2', x: 330, y: 230, rotation: 90, beat: 2 },
        ],
      },
      // Overhead Single Hard Key Lamp
      {
        id: 'noir-light-top',
        type: 'light',
        name: 'Overhead Practical Lamp (Single bulb)',
        fixtureType: 'spotlight',
        x: 400,
        y: 310,
        rotation: 90,
        colorTemp: 3000,
        intensity: 95,
        beamAngle: 60,
        throwDistance: 160,
        fixtureModel: 'Overhead Enamel Shade 500W',
      },
      // Leko hard rim through mirror
      {
        id: 'noir-light-rim',
        type: 'light',
        name: 'Leko Hard Rim (Venetian Blind Gobo)',
        fixtureType: 'spotlight',
        x: 180,
        y: 450,
        rotation: 315,
        colorTemp: 5600,
        intensity: 80,
        beamAngle: 26,
        throwDistance: 320,
        fixtureModel: 'ETC Source 4 Leko with Venetian Gobo',
      },
      // Camera A: Detective POV / Suspect Low Angle Close-up
      {
        id: 'noir-cam-a',
        type: 'camera',
        name: 'Cam A',
        cameraLabel: 'A',
        color: '#0284c7',
        x: 440,
        y: 310,
        rotation: 180,
        focalLength: 35,
        sensorFormat: 'Super35',
        fovAngle: calculateFovAngle(35, 'Super35'),
        aspectRatio: '2.39:1',
        cameraHeight: 'Low Angle',
        rigType: 'Tripod',
        throwDistance: 200,
        associatedShotId: 'shot-2a',
        path: [],
      },
      // Camera B: Dutch Angle Profile
      {
        id: 'noir-cam-b',
        type: 'camera',
        name: 'Cam B',
        cameraLabel: 'B',
        color: '#dc2626',
        x: 400,
        y: 470,
        rotation: 270,
        focalLength: 28,
        sensorFormat: 'Super35',
        fovAngle: calculateFovAngle(28, 'Super35'),
        aspectRatio: '2.39:1',
        cameraHeight: 'Eye Level',
        rigType: 'Handheld',
        throwDistance: 260,
        associatedShotId: 'shot-2b',
        path: [],
      },
    ],
    shots: [
      {
        id: 'shot-2a',
        sceneNumber: '2',
        shotNumber: '2/1',
        name: 'Suspect Low Angle Push-In',
        cameraId: 'noir-cam-a',
        cameraLabel: 'A',
        shotSize: 'CU',
        lensMm: 35,
        cameraAngle: 'Low Angle',
        movement: 'Dolly In',
        aspectRatio: '2.39:1',
        frameRate: 24,
        subjectActorIds: ['actor-suspect'],
        equipmentNotes: '35mm Prime at T1.5, heavy top down shadow in eye sockets.',
        framingDescription: 'Intimidating low angle close up framing Marcus trapped in pool of hard light.',
        actionScriptNotes: 'Marcus sweats under interrogation, refusing to answer.',
        status: 'ready',
        takesCount: 2,
        estDurationSeconds: 30,
        order: 1,
      },
      {
        id: 'shot-2b',
        sceneNumber: '2',
        shotNumber: '2/2',
        name: 'Noir Dutch Angle Two-Shot',
        cameraId: 'noir-cam-b',
        cameraLabel: 'A',
        shotSize: 'MS',
        lensMm: 28,
        cameraAngle: 'Eye Level',
        movement: 'Handheld',
        aspectRatio: '2.39:1',
        frameRate: 24,
        subjectActorIds: ['actor-suspect', 'actor-detective'],
        equipmentNotes: 'Handheld with 15-degree Dutch tilt to induce psychological unease.',
        framingDescription: 'Both characters in profile with extreme contrast shadows and venetian blind slashes across wall.',
        actionScriptNotes: 'Miller circles Marcus like a predator.',
        status: 'planned',
        takesCount: 0,
        estDurationSeconds: 40,
        order: 2,
      },
    ],
  },
];
